# Simple workflow for deploying static content to GitHub Pages
name: Deploy leaflet previewer

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - app/**
      - utils.js
      - workdocs/accessibility/**

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  DeployLeafletPreviewer:
    name: 'Deploy Leaflet Previewer'
    uses: pdmfcsa/leaflet-preview/.github/workflows/static.yml@main